<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.PowerBI.Api" Version="5.1.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.13" />
    <PackageReference Include="Stripe.net" Version="52.4.0" />
  </ItemGroup>

  <ItemGroup>
	  <None Include="Data\SeedData\**" CopyToOutputDirectory="PreserveNewest" />    <!--It means make sure the JSON files are copied into the output alongside the compiled application so the running app can find them.-->
    <ProjectReference Include="..\Core\Core.csproj" />                              <!--"PreserveNewest" mean Copy the file when necessary, but don't copy it again if the output already has the latest version.-->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>
